pipeline:
  identifier: Build_git_pratice_files1_1731577766579
  name: Build git-pratice-files1
  orgIdentifier: default
  projectIdentifier: firstproject
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: githubconnect
        repoName: git-pratice-files1
  stages:
    - stage:
        name: dev
        identifier: dev
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: echo "ls -la"
